INSERT INTO POSTS (USER_ID, BODY)
VALUES (4, "This is my second post on this forum.");
COMMIT;
SELECT * FROM POSTS;

UPDATE POSTS
SET BODY = "TO DELETE"
WHERE ID = 8;
COMMIT;
SELECT * FROM POSTS;

DELETE FROM POSTS
WHERE ID = 8;
COMMIT;
SELECT * FROM POSTS;
